// SPDX-License-Identifier: GPL-3.0-or-later
import { ALIGNMENTS, FACTIONS } from "./utils.js";

function timing(startup, active, recovery) {
  return { startupMs: startup, activeMs: active, recoveryMs: recovery };
}

function melee(damage, range, cooldown, arcDeg = 90, knockback = 105, actionTiming = timing(90, 100, 180)) {
  return {
    kind: "melee",
    damage,
    range,
    cooldown,
    arcDeg,
    knockback,
    timing: actionTiming,
  };
}

function projectile(
  damage,
  range,
  cooldown,
  projectileSpeed,
  projectileRadius = 5,
  actionTiming = timing(110, 90, 210),
) {
  return {
    kind: "projectile",
    damage,
    range,
    cooldown,
    projectileSpeed,
    projectileRadius,
    timing: actionTiming,
  };
}

function special(id, name, description, cooldown, kind, actionTiming, extra = {}) {
  return {
    id,
    name,
    description,
    cooldown,
    kind,
    timing: actionTiming,
    ...extra,
  };
}

export const UNIT_DEFS = {
  CC: {
    id: "CC",
    name: "Core Commander",
    displayName: "Core Commander",
    faction: FACTIONS.SOLAR,
    alignment: ALIGNMENTS[FACTIONS.SOLAR],
    isCommandUnit: true,
    maxHp: 120,
    speed: 166,
    radius: 24,
    attack: melee(16, 92, 0.58, 100, 115, timing(90, 100, 190)),
    special: special(
      "aegisBurst",
      "Aegis Burst",
      "Reduces incoming damage for 2.2 seconds.",
      4.8,
      "shield",
      timing(120, 180, 240),
      { durationMs: 2000, damageScale: 0.58 },
    ),
    boardMovement: { type: "king", maxSteps: 1 },
    boardAbility: null,
    visual: { shape: "hex", abbr: "CC", glow: "solar" },
    aiHints: { role: "balanced", protectCommand: true },
    balanceNotes: "Durable balanced command fighter.",
  },
  PS: {
    id: "PS",
    name: "Photon Striker",
    displayName: "Photon Striker",
    faction: FACTIONS.SOLAR,
    alignment: ALIGNMENTS[FACTIONS.SOLAR],
    isCommandUnit: false,
    maxHp: 90,
    speed: 242,
    radius: 21,
    attack: melee(16, 70, 0.5, 90, 130, timing(65, 80, 175)),
    special: special(
      "photonDash",
      "Photon Dash",
      "Directional dash that damages the first fighter crossed.",
      4.2,
      "dash",
      timing(70, 280, 210),
      { dashSpeed: 650, damageMultiplier: 1.65, knockback: 190 },
    ),
    boardMovement: { type: "runner", maxSteps: 3 },
    boardAbility: null,
    visual: { shape: "pentagon", abbr: "PS", glow: "solar" },
    aiHints: { role: "melee" },
    balanceNotes: "Fast melee skirmisher with committed burst movement.",
  },
  AS: {
    id: "AS",
    name: "Arc Sniper",
    displayName: "Arc Sniper",
    faction: FACTIONS.SOLAR,
    alignment: ALIGNMENTS[FACTIONS.SOLAR],
    isCommandUnit: false,
    maxHp: 78,
    speed: 180,
    radius: 20,
    attack: projectile(18, 520, 0.82, 445, 5, timing(120, 90, 250)),
    special: special(
      "arcLance",
      "Arc Lance",
      "Telegraphed high-speed shot with long reach.",
      6,
      "chargedProjectile",
      timing(420, 100, 300),
      { damageMultiplier: 2, range: 760, projectileSpeed: 720, projectileRadius: 7 },
    ),
    boardMovement: { type: "line", maxSteps: 4 },
    boardAbility: null,
    visual: { shape: "diamond", abbr: "AS", glow: "solar" },
    aiHints: { role: "ranged" },
    balanceNotes: "Fragile precision fighter with readable commitment.",
  },
  SD: {
    id: "SD",
    name: "Shield Drone",
    displayName: "Shield Drone",
    faction: FACTIONS.SOLAR,
    alignment: ALIGNMENTS[FACTIONS.SOLAR],
    isCommandUnit: false,
    maxHp: 115,
    speed: 146,
    radius: 25,
    attack: projectile(12, 310, 0.63, 340, 6, timing(105, 90, 210)),
    special: special(
      "barrierWall",
      "Barrier Wall",
      "Deploys a temporary wall that blocks enemy projectiles.",
      5,
      "barrier",
      timing(100, 160, 210),
      { durationMs: 2800, width: 18, height: 130, distance: 58 },
    ),
    boardMovement: { type: "ortho", maxSteps: 2 },
    boardAbility: null,
    visual: { shape: "tank", abbr: "SD", glow: "solar" },
    aiHints: { role: "defender" },
    balanceNotes: "Defensive ranged fighter with projectile control.",
  },
  PM: {
    id: "PM",
    name: "Pulse Medic",
    displayName: "Pulse Medic",
    faction: FACTIONS.SOLAR,
    alignment: ALIGNMENTS[FACTIONS.SOLAR],
    isCommandUnit: false,
    maxHp: 88,
    speed: 182,
    radius: 21,
    attack: projectile(13, 320, 0.64, 385, 5, timing(95, 85, 205)),
    special: special(
      "renewalPulse",
      "Renewal Pulse",
      "Repairs itself and fires two low-power pulses.",
      4.8,
      "repairBurst",
      timing(120, 170, 220),
      { heal: 22, damageMultiplier: 0.78, spreadRad: 0.12 },
    ),
    boardMovement: { type: "ortho", maxSteps: 2 },
    boardAbility: "repairAdjacentAlly",
    visual: { shape: "orb", abbr: "PM", glow: "solar" },
    aiHints: { role: "support" },
    balanceNotes: "Sustain support with modest directional pressure.",
  },
  NW: {
    id: "NW",
    name: "Nova Walker",
    displayName: "Nova Walker",
    faction: FACTIONS.SOLAR,
    alignment: ALIGNMENTS[FACTIONS.SOLAR],
    isCommandUnit: false,
    maxHp: 132,
    speed: 124,
    radius: 27,
    attack: melee(20, 100, 0.94, 108, 145, timing(165, 110, 300)),
    special: special(
      "novaBurst",
      "Nova Burst",
      "Slow telegraphed blast around the Walker.",
      6,
      "radialBlast",
      timing(520, 120, 320),
      { radius: 158, damageMultiplier: 1.35, knockback: 215 },
    ),
    boardMovement: { type: "heavy", maxSteps: 2 },
    boardAbility: null,
    visual: { shape: "tank", abbr: "NW", glow: "solar" },
    aiHints: { role: "heavy" },
    balanceNotes: "Slow heavy fighter that controls close space.",
  },
  NO: {
    id: "NO",
    name: "Null Overlord",
    displayName: "Null Overlord",
    faction: FACTIONS.VOID,
    alignment: ALIGNMENTS[FACTIONS.VOID],
    isCommandUnit: true,
    maxHp: 120,
    speed: 166,
    radius: 24,
    attack: melee(16, 92, 0.58, 100, 115, timing(90, 100, 190)),
    special: special(
      "nullAura",
      "Null Aura",
      "Damages nearby opponents for 2.8 seconds.",
      5,
      "aura",
      timing(120, 180, 250),
      { durationMs: 2200, radius: 108, dps: 6 },
    ),
    boardMovement: { type: "king", maxSteps: 1 },
    boardAbility: null,
    visual: { shape: "hex", abbr: "NO", glow: "void" },
    aiHints: { role: "balanced", protectCommand: true },
    balanceNotes: "Balanced command fighter with close-area pressure.",
  },
  RC: {
    id: "RC",
    name: "Razor Crawler",
    displayName: "Razor Crawler",
    faction: FACTIONS.VOID,
    alignment: ALIGNMENTS[FACTIONS.VOID],
    isCommandUnit: false,
    maxHp: 90,
    speed: 242,
    radius: 21,
    attack: melee(16, 70, 0.5, 90, 130, timing(65, 80, 175)),
    special: special(
      "razorLeap",
      "Razor Leap",
      "Directional leap that damages and knocks back on contact.",
      4.2,
      "dash",
      timing(80, 270, 220),
      { dashSpeed: 630, damageMultiplier: 1.65, knockback: 210 },
    ),
    boardMovement: { type: "runner", maxSteps: 3 },
    boardAbility: null,
    visual: { shape: "pentagon", abbr: "RC", glow: "void" },
    aiHints: { role: "melee" },
    balanceNotes: "Fast melee pressure with a committed leap.",
  },
  EC: {
    id: "EC",
    name: "Entropy Cannon",
    displayName: "Entropy Cannon",
    faction: FACTIONS.VOID,
    alignment: ALIGNMENTS[FACTIONS.VOID],
    isCommandUnit: false,
    maxHp: 88,
    speed: 136,
    radius: 24,
    attack: projectile(22, 460, 1.1, 270, 9, timing(175, 110, 315)),
    special: special(
      "entropyShell",
      "Entropy Shell",
      "Fires a large slow projectile with heavy impact.",
      6,
      "heavyProjectile",
      timing(360, 120, 330),
      { damageMultiplier: 1.75, range: 620, projectileSpeed: 225, projectileRadius: 14 },
    ),
    boardMovement: { type: "line", maxSteps: 4 },
    boardAbility: null,
    visual: { shape: "diamond", abbr: "EC", glow: "void" },
    aiHints: { role: "ranged" },
    balanceNotes: "Durable artillery with slow, readable ordnance.",
  },
  GW: {
    id: "GW",
    name: "Glitch Wraith",
    displayName: "Glitch Wraith",
    faction: FACTIONS.VOID,
    alignment: ALIGNMENTS[FACTIONS.VOID],
    isCommandUnit: false,
    maxHp: 80,
    speed: 246,
    radius: 20,
    attack: projectile(13, 300, 0.6, 410, 4, timing(80, 80, 205)),
    special: special(
      "phaseBlink",
      "Phase Blink",
      "Blinks in the facing direction with brief invulnerability.",
      4.6,
      "blink",
      timing(80, 120, 210),
      { distance: 155, invulnerableMs: 700 },
    ),
    boardMovement: { type: "phase", maxSteps: 3 },
    boardAbility: "phaseThroughOneOccupied",
    visual: { shape: "orb", abbr: "GW", glow: "void" },
    aiHints: { role: "evasive" },
    balanceNotes: "Mobile disruptor with a directed defensive blink.",
  },
  CB: {
    id: "CB",
    name: "Corruptor Bot",
    displayName: "Corruptor Bot",
    faction: FACTIONS.VOID,
    alignment: ALIGNMENTS[FACTIONS.VOID],
    isCommandUnit: false,
    maxHp: 88,
    speed: 182,
    radius: 21,
    attack: projectile(13, 320, 0.64, 385, 5, timing(95, 85, 205)),
    special: special(
      "corruptorSpread",
      "Corruptor Spread",
      "Fires three directional projectiles in a controlled spread.",
      4.8,
      "spread",
      timing(120, 170, 220),
      { count: 3, damageMultiplier: 0.9, spreadRad: 0.14 },
    ),
    boardMovement: { type: "ortho", maxSteps: 2 },
    boardAbility: "weakenAdjacentEnemy",
    visual: { shape: "orb", abbr: "CB", glow: "void" },
    aiHints: { role: "support" },
    balanceNotes: "Debuff support with a space-covering burst.",
  },
  GB: {
    id: "GB",
    name: "Gravity Bruiser",
    displayName: "Gravity Bruiser",
    faction: FACTIONS.VOID,
    alignment: ALIGNMENTS[FACTIONS.VOID],
    isCommandUnit: false,
    maxHp: 150,
    speed: 120,
    radius: 27,
    attack: melee(24, 104, 0.9, 112, 155, timing(165, 110, 300)),
    special: special(
      "gravityCone",
      "Gravity Cone",
      "Pulls targets in front, then delivers a close impact.",
      6,
      "gravityCone",
      timing(180, 1500, 300),
      { range: 285, arcDeg: 72, pullForce: 225, impactRange: 122, damageMultiplier: 1.05 },
    ),
    boardMovement: { type: "heavy", maxSteps: 2 },
    boardAbility: null,
    visual: { shape: "tank", abbr: "GB", glow: "void" },
    aiHints: { role: "heavy" },
    balanceNotes: "Slow heavy fighter with directional control.",
  },
};

export const INITIAL_VOID_ROW = ["EC", "RC", "GW", "CB", "NO", "GB", "RC", "EC", "GW"];
export const INITIAL_SOLAR_ROW = ["AS", "PS", "SD", "PM", "CC", "NW", "PS", "AS", "SD"];
